files:
  include: 'sass/**/*.s+(a|c)ss'
  ignore:
    - 'sass/vendor/**/*.scss'
    - 'sass/tests/**/*.scss'
rules:
  no-ids: 1
  no-important: 1
  indentation:
    - 1
    -
      size: 4
  property-sort-order:
    - 0
